### ISSUE TITLE
How to manually set the user status?

### ISSUE THREAD

**Issue by dominicarrojado** [mizzao/meteor-user-status#84]
What if user wants his status to be away or offline? How can I do that in this package? Thanks :)

**Comment by mizzao** [comment]
This package isn't really meant for doing that. You can use the idle monitoring to set an "away" status, and offline is automatically set when a user is not connected.

Of course, you can always build your own status on top of this that allows the user to override it (e.g. in your frontend).

**Comment by d4nyll** [comment]
This would be a good feature to have, since some people might like to remain 'invisible' even when they're online.

Please let me know if the following would work:

* Add a `invisible` property to the `status` property, which a user can set manually
* In the publish function, instead of 

```
Meteor.publish("userStatus", function() {
  return Meteor.users.find({ "status.online": true }, { fields: { ... } });
});
```

You have:

```
Meteor.publish("userStatus", function() {
  return Meteor.users.find({ "status.online": true, "status.invisible": false }, { fields: { ... } });
});
```

**Comment by mizzao** [comment]
I think you could just implement it yourself, e.g. on the `Meteor.users` collection, and just multiplex the appropriate value to display on the client? I don't see how this would be any more complicated than putting it in the package itself, which I think would be out of scope.
