### ISSUE TITLE
Getting idle status on angular-meteor?

### ISSUE THREAD

**Issue by shantanubhadoria** [mizzao/meteor-user-status#89]
Thanks for writing this module.
I am not using the iron router as I am working with Angular Meteor. 
Is there a way to track user **idle** status with angularjs frontend? I looked around for a while and could not find any example for it.

**Comment by mizzao** [comment]
Sorry, GitHub issues aren't for support requests. If you can identify a bug with the package, please post some code or an app that reproduces it and specify how to do so.

I would highly recommend learning how Angular and Meteor work together rather than just trying to copy some example code from somewhere else.
